---
- name: default 
  box: centos/7
  cpus: 2
  memory: 4096 
  private_ip: 10.0.10.10
  package_manager: yum
  packages:
  - epel-release
  - git
  - vim
  - java
  - unzip
  - maven
  - wget
  - docker
  scripts:
  - vim
  - docker
  - jenkins
#  - tracker_docker
#  - rabbit_mq
#  - producer
...

