---
- name: osgi_camel 
  box: centos/7
  cpus: 2
  memory: 4096 
  private_ip: 10.0.10.10
  package_manager: yum
  packages:
  - git
  - vim
  - java
  - unzip
  - maven
  - wget
  - docker
  scripts:
  - vim
  - docker
  - tracker_docker
  - rabbit_mq
  - producer
...

